// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: test_dashboard

#ifndef UI_PAGEMENU_H
#define UI_PAGEMENU_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_PageMenu
extern void ui_PageMenu_screen_init(void);
extern void ui_PageMenu_screen_destroy(void);
extern lv_obj_t * ui_PageMenu;
extern lv_obj_t * ui_PageMenu_Panel4;
extern void ui_event_PageMenu_BtnMiniMax1(lv_event_t * e);
extern lv_obj_t * ui_PageMenu_BtnMiniMax1;
extern void ui_event_PageMenu_BtnLeds(lv_event_t * e);
extern lv_obj_t * ui_PageMenu_BtnLeds;
extern void ui_event_PageMenu_Btnconfig(lv_event_t * e);
extern lv_obj_t * ui_PageMenu_Btnconfig;
extern void ui_event_PageMenu_BtnDispaly(lv_event_t * e);
extern lv_obj_t * ui_PageMenu_BtnDispaly;
extern void ui_event_PageMenu_BtnMiniMax(lv_event_t * e);
extern lv_obj_t * ui_PageMenu_BtnMiniMax;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

