// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: test_dashboard

#include "../ui.h"

lv_obj_t * ui_PageLEDs = NULL;
lv_obj_t * ui_PageLEDs_Button1 = NULL;
lv_obj_t * ui_PageLEDs_Button2 = NULL;
lv_obj_t * ui_PageLEDs_Button3 = NULL;
lv_obj_t * ui_PageLEDs_Label3 = NULL;
// event funtions

// build funtions

void ui_PageLEDs_screen_init(void)
{
    ui_PageLEDs = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_PageLEDs, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_PageLEDs, &ui_img_gpdash_70_config_led_std_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PageLEDs_Button1 = lv_btn_create(ui_PageLEDs);
    lv_obj_set_width(ui_PageLEDs_Button1, 72);
    lv_obj_set_height(ui_PageLEDs_Button1, 50);
    lv_obj_set_x(ui_PageLEDs_Button1, 204);
    lv_obj_set_y(ui_PageLEDs_Button1, 52);
    lv_obj_set_align(ui_PageLEDs_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PageLEDs_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_PageLEDs_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PageLEDs_Button2 = lv_btn_create(ui_PageLEDs);
    lv_obj_set_width(ui_PageLEDs_Button2, 72);
    lv_obj_set_height(ui_PageLEDs_Button2, 50);
    lv_obj_set_x(ui_PageLEDs_Button2, 296);
    lv_obj_set_y(ui_PageLEDs_Button2, 48);
    lv_obj_set_align(ui_PageLEDs_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PageLEDs_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_PageLEDs_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PageLEDs_Button3 = lv_btn_create(ui_PageLEDs);
    lv_obj_set_width(ui_PageLEDs_Button3, 72);
    lv_obj_set_height(ui_PageLEDs_Button3, 50);
    lv_obj_set_x(ui_PageLEDs_Button3, 385);
    lv_obj_set_y(ui_PageLEDs_Button3, 54);
    lv_obj_set_align(ui_PageLEDs_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PageLEDs_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_PageLEDs_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PageLEDs_Label3 = lv_label_create(ui_PageLEDs);
    lv_obj_set_width(ui_PageLEDs_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PageLEDs_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PageLEDs_Label3, 231);
    lv_obj_set_y(ui_PageLEDs_Label3, -4);
    lv_obj_set_align(ui_PageLEDs_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PageLEDs_Label3, "text");

}

void ui_PageLEDs_screen_destroy(void)
{
    if(ui_PageLEDs) lv_obj_del(ui_PageLEDs);

    // NULL screen variables
    ui_PageLEDs = NULL;
    ui_PageLEDs_Button1 = NULL;
    ui_PageLEDs_Button2 = NULL;
    ui_PageLEDs_Button3 = NULL;
    ui_PageLEDs_Label3 = NULL;

}
