// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: test_dashboard

#ifndef UI_PAGELEDS_H
#define UI_PAGELEDS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_PageLEDs
extern void ui_PageLEDs_screen_init(void);
extern void ui_PageLEDs_screen_destroy(void);
extern lv_obj_t * ui_PageLEDs;
extern lv_obj_t * ui_PageLEDs_Button1;
extern lv_obj_t * ui_PageLEDs_Button2;
extern lv_obj_t * ui_PageLEDs_Button3;
extern lv_obj_t * ui_PageLEDs_Label3;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

