// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: test_dashboard

#ifndef UI_PAGELOGO_H
#define UI_PAGELOGO_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_PageLogo
extern void ui_PageLogo_screen_init(void);
extern void ui_PageLogo_screen_destroy(void);
extern lv_obj_t * ui_PageLogo;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

