// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: test_dashboard

#ifndef UI_PAGEMINI_MAX_H
#define UI_PAGEMINI_MAX_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_PageMINI_MAX
extern void ui_PageMINI_MAX_screen_init(void);
extern void ui_PageMINI_MAX_screen_destroy(void);
extern lv_obj_t * ui_PageMINI_MAX;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

