// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: test_dashboard

#include "../ui.h"

lv_obj_t * ui_PageMenu = NULL;
lv_obj_t * ui_PageMenu_Panel4 = NULL;
lv_obj_t * ui_PageMenu_BtnMiniMax1 = NULL;
lv_obj_t * ui_PageMenu_BtnLeds = NULL;
lv_obj_t * ui_PageMenu_Btnconfig = NULL;
lv_obj_t * ui_PageMenu_BtnDispaly = NULL;
lv_obj_t * ui_PageMenu_BtnMiniMax = NULL;
// event funtions
void ui_event_PageMenu_BtnMiniMax1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_LONG_PRESSED) {
        _ui_screen_change(&ui_PageMINI_MAX, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_PageMINI_MAX_screen_init);
    }
}

void ui_event_PageMenu_BtnLeds(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_LONG_PRESSED) {
        _ui_screen_change(&ui_PageLEDs, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_PageLEDs_screen_init);
    }
}

void ui_event_PageMenu_Btnconfig(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_LONG_PRESSED) {
        _ui_screen_change(&ui_PageCONFIG, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_PageCONFIG_screen_init);
    }
}

void ui_event_PageMenu_BtnDispaly(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_LONG_PRESSED) {
        _ui_screen_change(&ui_PageDISPLAY, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_PageDISPLAY_screen_init);
    }
}

void ui_event_PageMenu_BtnMiniMax(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_LONG_PRESSED) {
        _ui_screen_change(&ui_PageMINI_MAX, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_PageMINI_MAX_screen_init);
    }
}

// build funtions

void ui_PageMenu_screen_init(void)
{
    ui_PageMenu = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_PageMenu, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE |
                      LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM);     /// Flags
    lv_obj_set_scrollbar_mode(ui_PageMenu, LV_SCROLLBAR_MODE_ACTIVE);
    lv_obj_set_scroll_dir(ui_PageMenu, LV_DIR_HOR);
    lv_obj_set_scroll_snap_x(ui_PageMenu, LV_SCROLL_SNAP_CENTER);
    lv_obj_set_scroll_snap_y(ui_PageMenu, LV_SCROLL_SNAP_CENTER);
    lv_obj_set_style_bg_img_src(ui_PageMenu, &ui_img_gddash_70_fond_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_PageMenu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_PageMenu, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PageMenu_Panel4 = lv_obj_create(ui_PageMenu);
    lv_obj_set_width(ui_PageMenu_Panel4, 1024);
    lv_obj_set_height(ui_PageMenu_Panel4, 600);
    lv_obj_set_x(ui_PageMenu_Panel4, 0);
    lv_obj_set_y(ui_PageMenu_Panel4, -1);
    lv_obj_set_align(ui_PageMenu_Panel4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PageMenu_Panel4, LV_OBJ_FLAG_SCROLL_ONE);     /// Flags
    lv_obj_clear_flag(ui_PageMenu_Panel4, LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);      /// Flags
    lv_obj_set_scroll_dir(ui_PageMenu_Panel4, LV_DIR_HOR);
    lv_obj_set_scroll_snap_x(ui_PageMenu_Panel4, LV_SCROLL_SNAP_CENTER);
    lv_obj_set_style_bg_img_src(ui_PageMenu_Panel4, &ui_img_gddash_70_fond_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_opa(ui_PageMenu_Panel4, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_PageMenu_BtnMiniMax1 = lv_imgbtn_create(ui_PageMenu_Panel4);
    lv_imgbtn_set_src(ui_PageMenu_BtnMiniMax1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_icon03_png, NULL);
    lv_imgbtn_set_src(ui_PageMenu_BtnMiniMax1, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_icon03_png, NULL);
    lv_obj_set_width(ui_PageMenu_BtnMiniMax1, 441);
    lv_obj_set_height(ui_PageMenu_BtnMiniMax1, 202);
    lv_obj_set_y(ui_PageMenu_BtnMiniMax1, 0);
    lv_obj_set_x(ui_PageMenu_BtnMiniMax1, lv_pct(-100));
    lv_obj_set_align(ui_PageMenu_BtnMiniMax1, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_PageMenu_BtnMiniMax1, LV_STATE_FOCUSED);       /// States
    lv_obj_add_flag(ui_PageMenu_BtnMiniMax1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_PageMenu_BtnMiniMax1,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM);     /// Flags
    lv_obj_set_scroll_dir(ui_PageMenu_BtnMiniMax1, LV_DIR_HOR);

    ui_PageMenu_BtnLeds = lv_imgbtn_create(ui_PageMenu_Panel4);
    lv_imgbtn_set_src(ui_PageMenu_BtnLeds, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_icon02_png, NULL);
    lv_imgbtn_set_src(ui_PageMenu_BtnLeds, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_icon02_png, NULL);
    lv_obj_set_width(ui_PageMenu_BtnLeds, 441);
    lv_obj_set_height(ui_PageMenu_BtnLeds, 202);
    lv_obj_set_y(ui_PageMenu_BtnLeds, 0);
    lv_obj_set_x(ui_PageMenu_BtnLeds, lv_pct(-50));
    lv_obj_set_align(ui_PageMenu_BtnLeds, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PageMenu_BtnLeds, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_PageMenu_BtnLeds,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM);     /// Flags
    lv_obj_set_scroll_dir(ui_PageMenu_BtnLeds, LV_DIR_HOR);

    ui_PageMenu_Btnconfig = lv_imgbtn_create(ui_PageMenu_Panel4);
    lv_imgbtn_set_src(ui_PageMenu_Btnconfig, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_icon01_png, NULL);
    lv_imgbtn_set_src(ui_PageMenu_Btnconfig, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_icon01_png, NULL);
    lv_obj_set_width(ui_PageMenu_Btnconfig, 441);
    lv_obj_set_height(ui_PageMenu_Btnconfig, 202);
    lv_obj_set_y(ui_PageMenu_Btnconfig, 0);
    lv_obj_set_x(ui_PageMenu_Btnconfig, lv_pct(100));
    lv_obj_set_align(ui_PageMenu_Btnconfig, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PageMenu_Btnconfig, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_PageMenu_Btnconfig,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM);     /// Flags
    lv_obj_set_scroll_dir(ui_PageMenu_Btnconfig, LV_DIR_HOR);

    ui_PageMenu_BtnDispaly = lv_imgbtn_create(ui_PageMenu_Panel4);
    lv_imgbtn_set_src(ui_PageMenu_BtnDispaly, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_icon04_png, NULL);
    lv_imgbtn_set_src(ui_PageMenu_BtnDispaly, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_icon04_png, NULL);
    lv_obj_set_width(ui_PageMenu_BtnDispaly, 441);
    lv_obj_set_height(ui_PageMenu_BtnDispaly, 202);
    lv_obj_set_y(ui_PageMenu_BtnDispaly, 0);
    lv_obj_set_x(ui_PageMenu_BtnDispaly, lv_pct(50));
    lv_obj_set_align(ui_PageMenu_BtnDispaly, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PageMenu_BtnDispaly, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_PageMenu_BtnDispaly,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM);     /// Flags
    lv_obj_set_scroll_dir(ui_PageMenu_BtnDispaly, LV_DIR_HOR);

    ui_PageMenu_BtnMiniMax = lv_imgbtn_create(ui_PageMenu_Panel4);
    lv_imgbtn_set_src(ui_PageMenu_BtnMiniMax, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_icon03_png, NULL);
    lv_imgbtn_set_src(ui_PageMenu_BtnMiniMax, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_icon03_png, NULL);
    lv_obj_set_width(ui_PageMenu_BtnMiniMax, 441);
    lv_obj_set_height(ui_PageMenu_BtnMiniMax, 202);
    lv_obj_set_align(ui_PageMenu_BtnMiniMax, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PageMenu_BtnMiniMax, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_PageMenu_BtnMiniMax,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE |
                      LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM);     /// Flags
    lv_obj_set_scroll_dir(ui_PageMenu_BtnMiniMax, LV_DIR_HOR);

    lv_obj_add_event_cb(ui_PageMenu_BtnMiniMax1, ui_event_PageMenu_BtnMiniMax1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PageMenu_BtnLeds, ui_event_PageMenu_BtnLeds, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PageMenu_Btnconfig, ui_event_PageMenu_Btnconfig, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PageMenu_BtnDispaly, ui_event_PageMenu_BtnDispaly, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PageMenu_BtnMiniMax, ui_event_PageMenu_BtnMiniMax, LV_EVENT_ALL, NULL);

}

void ui_PageMenu_screen_destroy(void)
{
    if(ui_PageMenu) lv_obj_del(ui_PageMenu);

    // NULL screen variables
    ui_PageMenu = NULL;
    ui_PageMenu_Panel4 = NULL;
    ui_PageMenu_BtnMiniMax1 = NULL;
    ui_PageMenu_BtnLeds = NULL;
    ui_PageMenu_Btnconfig = NULL;
    ui_PageMenu_BtnDispaly = NULL;
    ui_PageMenu_BtnMiniMax = NULL;

}
