// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: test_dashboard

#include "../ui.h"

lv_obj_t * ui_PageLogo = NULL;
// event funtions

// build funtions

void ui_PageLogo_screen_init(void)
{
    ui_PageLogo = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_PageLogo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_PageLogo, &ui_img_logo_loading_1024x600_70_png, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_PageLogo_screen_destroy(void)
{
    if(ui_PageLogo) lv_obj_del(ui_PageLogo);

    // NULL screen variables
    ui_PageLogo = NULL;

}
