// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: test_dashboard

#include "../ui.h"

lv_obj_t * ui_PageCONFIG = NULL;
// event funtions

// build funtions

void ui_PageCONFIG_screen_init(void)
{
    ui_PageCONFIG = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_PageCONFIG, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_PageCONFIG, &ui_img_gauche_10000_fond_png, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_PageCONFIG_screen_destroy(void)
{
    if(ui_PageCONFIG) lv_obj_del(ui_PageCONFIG);

    // NULL screen variables
    ui_PageCONFIG = NULL;

}
