// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: test_dashboard

#include "../ui.h"

lv_obj_t * ui_PageDISPLAY = NULL;
lv_obj_t * ui_PageDISPLAY_Dropdown1 = NULL;
lv_obj_t * ui_PageDISPLAY_Label1 = NULL;
// event funtions

// build funtions

void ui_PageDISPLAY_screen_init(void)
{
    ui_PageDISPLAY = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_PageDISPLAY, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_PageDISPLAY, &ui_img_gauche_10000_curseur_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PageDISPLAY_Dropdown1 = lv_dropdown_create(ui_PageDISPLAY);
    lv_dropdown_set_options(ui_PageDISPLAY_Dropdown1, "MaxxECU\nLink\nECUMASTER\nMegasquirt\nSodemo EV11");
    lv_obj_set_width(ui_PageDISPLAY_Dropdown1, 213);
    lv_obj_set_height(ui_PageDISPLAY_Dropdown1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PageDISPLAY_Dropdown1, -287);
    lv_obj_set_y(ui_PageDISPLAY_Dropdown1, -101);
    lv_obj_set_align(ui_PageDISPLAY_Dropdown1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PageDISPLAY_Dropdown1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_PageDISPLAY_Label1 = lv_label_create(ui_PageDISPLAY);
    lv_obj_set_width(ui_PageDISPLAY_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PageDISPLAY_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PageDISPLAY_Label1, -370);
    lv_obj_set_y(ui_PageDISPLAY_Label1, -139);
    lv_obj_set_align(ui_PageDISPLAY_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PageDISPLAY_Label1, "ECU");

}

void ui_PageDISPLAY_screen_destroy(void)
{
    if(ui_PageDISPLAY) lv_obj_del(ui_PageDISPLAY);

    // NULL screen variables
    ui_PageDISPLAY = NULL;
    ui_PageDISPLAY_Dropdown1 = NULL;
    ui_PageDISPLAY_Label1 = NULL;

}
