// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: test_dashboard

#ifndef UI_PAGEDISPLAY_H
#define UI_PAGEDISPLAY_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_PageDISPLAY
extern void ui_PageDISPLAY_screen_init(void);
extern void ui_PageDISPLAY_screen_destroy(void);
extern lv_obj_t * ui_PageDISPLAY;
extern lv_obj_t * ui_PageDISPLAY_Dropdown1;
extern lv_obj_t * ui_PageDISPLAY_Label1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

