// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: test_dashboard

#include "../ui.h"

lv_obj_t * ui_PageLogo = NULL;
// event funtions
void ui_event_PageLogo(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        _ui_screen_change(&ui_PageMenu, LV_SCR_LOAD_ANIM_OVER_LEFT, 500, 3000, &ui_PageMenu_screen_init);
    }
}

// build funtions

void ui_PageLogo_screen_init(void)
{
    ui_PageLogo = lv_obj_create(NULL);
    lv_obj_add_flag(ui_PageLogo, LV_OBJ_FLAG_SCROLL_ONE);     /// Flags
    lv_obj_clear_flag(ui_PageLogo, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM);      /// Flags
    lv_obj_set_style_bg_img_src(ui_PageLogo, &ui_img_logo_loading_1024x600_70_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_PageLogo, ui_event_PageLogo, LV_EVENT_ALL, NULL);

}

void ui_PageLogo_screen_destroy(void)
{
    if(ui_PageLogo) lv_obj_del(ui_PageLogo);

    // NULL screen variables
    ui_PageLogo = NULL;

}
