// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: test_dashboard

#include "../ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_Screen1_Panel1 = NULL;
lv_obj_t * ui_Screen1_Btnconfig = NULL;
lv_obj_t * ui_Screen1_Panel2 = NULL;
lv_obj_t * ui_Screen1_BtnDispaly = NULL;
lv_obj_t * ui_Screen1_Panel3 = NULL;
lv_obj_t * ui_Screen1_BtnMiniMax = NULL;
lv_obj_t * ui_Screen1_Panel4 = NULL;
lv_obj_t * ui_Screen1_BtnLeds = NULL;
// event funtions
void ui_event_Screen1_Btnconfig(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_LONG_PRESSED) {
        _ui_screen_change(&ui_PageCONFIG, LV_SCR_LOAD_ANIM_FADE_ON, 500, 10, &ui_PageCONFIG_screen_init);
    }
}

void ui_event_Screen1_BtnDispaly(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_LONG_PRESSED) {
        _ui_screen_change(&ui_PageDISPLAY, LV_SCR_LOAD_ANIM_FADE_ON, 500, 10, &ui_PageDISPLAY_screen_init);
    }
}

void ui_event_Screen1_BtnMiniMax(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_LONG_PRESSED) {
        _ui_screen_change(&ui_PageMINI_MAX, LV_SCR_LOAD_ANIM_FADE_ON, 500, 10, &ui_PageMINI_MAX_screen_init);
    }
}

void ui_event_Screen1_BtnLeds(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_LONG_PRESSED) {
        _ui_screen_change(&ui_PageLEDs, LV_SCR_LOAD_ANIM_FADE_ON, 500, 10, &ui_PageLEDs_screen_init);
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLL_CHAIN);      /// Flags
    lv_obj_set_scrollbar_mode(ui_Screen1, LV_SCROLLBAR_MODE_ON);
    lv_obj_set_scroll_snap_x(ui_Screen1, LV_SCROLL_SNAP_CENTER);
    lv_obj_set_flex_flow(ui_Screen1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Screen1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_style_bg_img_src(ui_Screen1, &ui_img_gddash_70_fond_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Screen1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Screen1, 150, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1_Panel1 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Screen1_Panel1, 441);
    lv_obj_set_height(ui_Screen1_Panel1, 202);
    lv_obj_set_x(ui_Screen1_Panel1, 604);
    lv_obj_set_y(ui_Screen1_Panel1, -7);
    lv_obj_set_align(ui_Screen1_Panel1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen1_Panel1, LV_OBJ_FLAG_SCROLL_ONE);     /// Flags
    lv_obj_clear_flag(ui_Screen1_Panel1, LV_OBJ_FLAG_SCROLL_CHAIN);      /// Flags
    lv_obj_set_scroll_snap_x(ui_Screen1_Panel1, LV_SCROLL_SNAP_CENTER);
    lv_obj_set_style_bg_color(ui_Screen1_Panel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Screen1_Panel1, LV_GRAD_DIR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1_Btnconfig = lv_imgbtn_create(ui_Screen1_Panel1);
    lv_imgbtn_set_src(ui_Screen1_Btnconfig, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_icon01_png, NULL);
    lv_imgbtn_set_src(ui_Screen1_Btnconfig, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_icon01_png, NULL);
    lv_obj_set_width(ui_Screen1_Btnconfig, 441);
    lv_obj_set_height(ui_Screen1_Btnconfig, 202);
    lv_obj_set_align(ui_Screen1_Btnconfig, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen1_Btnconfig, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Screen1_Btnconfig,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLL_CHAIN);    /// Flags
    lv_obj_set_scroll_dir(ui_Screen1_Btnconfig, LV_DIR_HOR);

    ui_Screen1_Panel2 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Screen1_Panel2, 441);
    lv_obj_set_height(ui_Screen1_Panel2, 202);
    lv_obj_set_x(ui_Screen1_Panel2, -1947);
    lv_obj_set_y(ui_Screen1_Panel2, 42);
    lv_obj_set_align(ui_Screen1_Panel2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen1_Panel2, LV_OBJ_FLAG_SCROLL_ONE);     /// Flags
    lv_obj_clear_flag(ui_Screen1_Panel2, LV_OBJ_FLAG_SCROLL_CHAIN);      /// Flags
    lv_obj_set_scroll_snap_x(ui_Screen1_Panel2, LV_SCROLL_SNAP_CENTER);
    lv_obj_set_style_bg_color(ui_Screen1_Panel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1_BtnDispaly = lv_imgbtn_create(ui_Screen1_Panel2);
    lv_imgbtn_set_src(ui_Screen1_BtnDispaly, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_icon04_png, NULL);
    lv_imgbtn_set_src(ui_Screen1_BtnDispaly, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_icon04_png, NULL);
    lv_obj_set_width(ui_Screen1_BtnDispaly, 441);
    lv_obj_set_height(ui_Screen1_BtnDispaly, 202);
    lv_obj_set_align(ui_Screen1_BtnDispaly, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen1_BtnDispaly, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Screen1_BtnDispaly,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLL_CHAIN);    /// Flags
    lv_obj_set_scroll_dir(ui_Screen1_BtnDispaly, LV_DIR_HOR);

    ui_Screen1_Panel3 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Screen1_Panel3, 441);
    lv_obj_set_height(ui_Screen1_Panel3, 202);
    lv_obj_set_align(ui_Screen1_Panel3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen1_Panel3, LV_OBJ_FLAG_SCROLL_ONE);     /// Flags
    lv_obj_clear_flag(ui_Screen1_Panel3, LV_OBJ_FLAG_SCROLL_CHAIN);      /// Flags
    lv_obj_set_scroll_snap_x(ui_Screen1_Panel3, LV_SCROLL_SNAP_CENTER);
    lv_obj_set_style_bg_color(ui_Screen1_Panel3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1_BtnMiniMax = lv_imgbtn_create(ui_Screen1_Panel3);
    lv_imgbtn_set_src(ui_Screen1_BtnMiniMax, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_icon03_png, NULL);
    lv_imgbtn_set_src(ui_Screen1_BtnMiniMax, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_icon03_png, NULL);
    lv_obj_set_width(ui_Screen1_BtnMiniMax, 441);
    lv_obj_set_height(ui_Screen1_BtnMiniMax, 202);
    lv_obj_set_align(ui_Screen1_BtnMiniMax, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen1_BtnMiniMax, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Screen1_BtnMiniMax,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLL_CHAIN);    /// Flags
    lv_obj_set_scroll_dir(ui_Screen1_BtnMiniMax, LV_DIR_HOR);

    ui_Screen1_Panel4 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Screen1_Panel4, 441);
    lv_obj_set_height(ui_Screen1_Panel4, 202);
    lv_obj_set_x(ui_Screen1_Panel4, 1108);
    lv_obj_set_y(ui_Screen1_Panel4, -10);
    lv_obj_set_align(ui_Screen1_Panel4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen1_Panel4, LV_OBJ_FLAG_SCROLL_ONE);     /// Flags
    lv_obj_clear_flag(ui_Screen1_Panel4, LV_OBJ_FLAG_SCROLL_CHAIN);      /// Flags
    lv_obj_set_scroll_snap_x(ui_Screen1_Panel4, LV_SCROLL_SNAP_CENTER);
    lv_obj_set_style_bg_color(ui_Screen1_Panel4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1_BtnLeds = lv_imgbtn_create(ui_Screen1_Panel4);
    lv_imgbtn_set_src(ui_Screen1_BtnLeds, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_icon02_png, NULL);
    lv_imgbtn_set_src(ui_Screen1_BtnLeds, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_icon02_png, NULL);
    lv_obj_set_width(ui_Screen1_BtnLeds, 441);
    lv_obj_set_height(ui_Screen1_BtnLeds, 202);
    lv_obj_set_align(ui_Screen1_BtnLeds, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen1_BtnLeds, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Screen1_BtnLeds,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLL_CHAIN);    /// Flags
    lv_obj_set_scroll_dir(ui_Screen1_BtnLeds, LV_DIR_HOR);

    lv_obj_add_event_cb(ui_Screen1_Btnconfig, ui_event_Screen1_Btnconfig, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen1_BtnDispaly, ui_event_Screen1_BtnDispaly, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen1_BtnMiniMax, ui_event_Screen1_BtnMiniMax, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen1_BtnLeds, ui_event_Screen1_BtnLeds, LV_EVENT_ALL, NULL);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_Screen1_Panel1 = NULL;
    ui_Screen1_Btnconfig = NULL;
    ui_Screen1_Panel2 = NULL;
    ui_Screen1_BtnDispaly = NULL;
    ui_Screen1_Panel3 = NULL;
    ui_Screen1_BtnMiniMax = NULL;
    ui_Screen1_Panel4 = NULL;
    ui_Screen1_BtnLeds = NULL;

}
