// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: test_dashboard

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Screen1_Panel1;
extern void ui_event_Screen1_Btnconfig(lv_event_t * e);
extern lv_obj_t * ui_Screen1_Btnconfig;
extern lv_obj_t * ui_Screen1_Panel2;
extern void ui_event_Screen1_BtnDispaly(lv_event_t * e);
extern lv_obj_t * ui_Screen1_BtnDispaly;
extern lv_obj_t * ui_Screen1_Panel3;
extern void ui_event_Screen1_BtnMiniMax(lv_event_t * e);
extern lv_obj_t * ui_Screen1_BtnMiniMax;
extern lv_obj_t * ui_Screen1_Panel4;
extern void ui_event_Screen1_BtnLeds(lv_event_t * e);
extern lv_obj_t * ui_Screen1_BtnLeds;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

