// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: test_dashboard

#ifndef _TEST_DASHBOARD_UI_H
#define _TEST_DASHBOARD_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_PageLogo.h"
#include "screens/ui_PageMenu.h"
#include "screens/ui_PageLEDs.h"
#include "screens/ui_PageDISPLAY.h"
#include "screens/ui_PageCONFIG.h"
#include "screens/ui_PageMINI_MAX.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_logo_loading_1024x600_70_png);    // assets/LOGO_loading_1024x600_70.png
LV_IMG_DECLARE(ui_img_gddash_70_fond_png);    // assets/GDDash_70_Fond.png
LV_IMG_DECLARE(ui_img_icon03_png);    // assets/icon03.png
LV_IMG_DECLARE(ui_img_icon02_png);    // assets/icon02.png
LV_IMG_DECLARE(ui_img_icon01_png);    // assets/icon01.png
LV_IMG_DECLARE(ui_img_icon04_png);    // assets/icon04.png
LV_IMG_DECLARE(ui_img_gpdash_70_config_led_std_png);    // assets/GPDash_70_Config_LED_Std.png
LV_IMG_DECLARE(ui_img_gauche_10000_curseur_png);    // assets/gauche_10000_curseur.png
LV_IMG_DECLARE(ui_img_gauche_10000_fond_png);    // assets/gauche_10000_fond.png
LV_IMG_DECLARE(ui_img_droite_10000_fond_png);    // assets/droite_10000_fond.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
